name: tests-i386

on: [push, pull_request]

jobs:
  tests-i386:
    name: tests-i386
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: install deps
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get -y install gcc-multilib g++-multilib
          sudo apt-get -y remove ubuntu-advantage-tools
          sudo apt-get -y install --allow-downgrades libgcc-s1:i386 libstdc++6:i386 libpcre3-dev:i386 libglib2.0-dev:i386 python3:i386 python3-apt:i386 libpython3-stdlib:i386 python3-pip

      - name: install python deps
        run: |
          pip install pytest

      - name: test 
        run: |
          pytest test_pysize.py
